---
kind: pipeline
name: default

steps:
- name: docker  
  image: plugins/docker
  settings:
    email: michael@michaeldasheep.com
    registry: http://git.20080608.xyz:5000
    repo: http://git.20080608.xyz:5000/sheep/michaeldasheep.com
    tags: latest