---
kind: pipeline
name: default

steps:
- name: docker  
  image: plugins/docker
  settings:
    email: michael@michaeldasheep.com
    username: michaeldasheep
    password:
      from_secret: password
    repo: michaeldasheep/michaeldasheep.com
    tags: latest