---
kind: pipeline
name: default

steps:
- name: docker  
  image: plugins/docker
  settings:
    email: michael@michaeldasheep.com
    registry: registry.20080608.xyz
    repo: registry.20080608.xyz/sheep/michaeldasheep.com
    tags: _$VERSION_