---
kind: pipeline
name: default

steps:
- name: docker  
  image: plugins/docker
  settings:
    username: michaeldasheep
    password:
      from_secret: docker-hub-password
    repo: michaeldasheep/michaeldasheep.com
    tags: ${IMAGETAG}
    dockerfile: ./Dockerfile