---
kind: pipeline
name: default

steps:
- name: docker  
  image: plugins/docker
  settings:
    email: michael@michaeldasheep.com
    registry: git.20080608.xyz
    username: sheep
    password:
      from_secret: password
    repo: git.20080608.xyz/sheep/michaeldasheep.coms
    tags: latest