---
kind: pipeline
name: default

steps:
- name: docker  
  image: plugins/docker
  settings:
    username: michaeldasheep
    password:
      from_secret: docker-hub-password
    tags: first-release-do-not-use-history
    dockerfile: ./Dockerfile